### ISSUE TITLE
Data rotation

### ISSUE THREAD

**Issue by SuJiaKuan** [SuJiaKuan/jagereye#66]
When an new event occurs, some new data will be stored in system, such as video clips and related metadata. The data increases day by day. If we do not clear any data, the disks may have no more space to store the new events data. So we need a data rotation scheme to clear older, unused data automatically. To fulfill the requirements, we need at least one of the following mechanisms:
- Clear data that were created long time ago (3 months, for example).
- Clear the oldest data when the number of stored data exceeds the upper bounds (For example, we only allow 10,000 events stored in system).

**Comment by SuJiaKuan** [comment]
The data rotation scheme should also considers to prevent clearing some persistent data, as mentioned in **SourceSending** part in #65.

**Comment by uniray7** [comment]
@SuJiaKuan 
I still cannot understand that we should prevent what kind of data be cleared? 
And why it is involved with **SourceSending** part in #65.
I guess you indicate that whenever frontend & backend cannot access network, the data should be persistent until servicemen come. Is is that right?
